// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: aragog/aragog.proto

package aragog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthReq is an empty body request but represents
// root health check message
type HealthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthReq) Reset() {
	*x = HealthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aragog_aragog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReq) ProtoMessage() {}

func (x *HealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_aragog_aragog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReq.ProtoReflect.Descriptor instead.
func (*HealthReq) Descriptor() ([]byte, []int) {
	return file_aragog_aragog_proto_rawDescGZIP(), []int{0}
}

// HealthResp represents the root response message for a health check
type HealthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *HealthResp) Reset() {
	*x = HealthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aragog_aragog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResp) ProtoMessage() {}

func (x *HealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_aragog_aragog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResp.ProtoReflect.Descriptor instead.
func (*HealthResp) Descriptor() ([]byte, []int) {
	return file_aragog_aragog_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// UserReq
type UserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *UserReq) Reset() {
	*x = UserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aragog_aragog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReq) ProtoMessage() {}

func (x *UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_aragog_aragog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReq.ProtoReflect.Descriptor instead.
func (*UserReq) Descriptor() ([]byte, []int) {
	return file_aragog_aragog_proto_rawDescGZIP(), []int{2}
}

func (x *UserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// InviteResp
type InviteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InviteResp) Reset() {
	*x = InviteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aragog_aragog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteResp) ProtoMessage() {}

func (x *InviteResp) ProtoReflect() protoreflect.Message {
	mi := &file_aragog_aragog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteResp.ProtoReflect.Descriptor instead.
func (*InviteResp) Descriptor() ([]byte, []int) {
	return file_aragog_aragog_proto_rawDescGZIP(), []int{3}
}

func (x *InviteResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// RemoveResp
type RemoveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveResp) Reset() {
	*x = RemoveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aragog_aragog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResp) ProtoMessage() {}

func (x *RemoveResp) ProtoReflect() protoreflect.Message {
	mi := &file_aragog_aragog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResp.ProtoReflect.Descriptor instead.
func (*RemoveResp) Descriptor() ([]byte, []int) {
	return file_aragog_aragog_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_aragog_aragog_proto protoreflect.FileDescriptor

var file_aragog_aragog_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x72, 0x61, 0x67, 0x6f, 0x67, 0x2f, 0x61, 0x72, 0x61, 0x67, 0x6f, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x61, 0x72, 0x61,
	0x67, 0x6f, 0x67, 0x22, 0x0b, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x22, 0x24, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a,
	0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x24, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xa8, 0x02, 0x0a, 0x06, 0x41, 0x72,
	0x61, 0x67, 0x6f, 0x67, 0x12, 0x60, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x12, 0x27, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x61, 0x72, 0x61, 0x67,
	0x6f, 0x67, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x2e, 0x61, 0x72, 0x61, 0x67, 0x6f, 0x67, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x25, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x61, 0x72, 0x61,
	0x67, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x2e, 0x61, 0x72, 0x61, 0x67, 0x6f, 0x67, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x25, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x61, 0x72, 0x61, 0x67,
	0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x2e, 0x61, 0x72, 0x61, 0x67, 0x6f, 0x67, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x61, 0x72, 0x61, 0x67, 0x6f,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aragog_aragog_proto_rawDescOnce sync.Once
	file_aragog_aragog_proto_rawDescData = file_aragog_aragog_proto_rawDesc
)

func file_aragog_aragog_proto_rawDescGZIP() []byte {
	file_aragog_aragog_proto_rawDescOnce.Do(func() {
		file_aragog_aragog_proto_rawDescData = protoimpl.X.CompressGZIP(file_aragog_aragog_proto_rawDescData)
	})
	return file_aragog_aragog_proto_rawDescData
}

var file_aragog_aragog_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aragog_aragog_proto_goTypes = []interface{}{
	(*HealthReq)(nil),  // 0: github.com.scaletrade.aragog.HealthReq
	(*HealthResp)(nil), // 1: github.com.scaletrade.aragog.HealthResp
	(*UserReq)(nil),    // 2: github.com.scaletrade.aragog.UserReq
	(*InviteResp)(nil), // 3: github.com.scaletrade.aragog.InviteResp
	(*RemoveResp)(nil), // 4: github.com.scaletrade.aragog.RemoveResp
}
var file_aragog_aragog_proto_depIdxs = []int32{
	0, // 0: github.com.scaletrade.aragog.Aragog.HealthCheck:input_type -> github.com.scaletrade.aragog.HealthReq
	2, // 1: github.com.scaletrade.aragog.Aragog.InviteUser:input_type -> github.com.scaletrade.aragog.UserReq
	2, // 2: github.com.scaletrade.aragog.Aragog.RemoveUser:input_type -> github.com.scaletrade.aragog.UserReq
	1, // 3: github.com.scaletrade.aragog.Aragog.HealthCheck:output_type -> github.com.scaletrade.aragog.HealthResp
	3, // 4: github.com.scaletrade.aragog.Aragog.InviteUser:output_type -> github.com.scaletrade.aragog.InviteResp
	4, // 5: github.com.scaletrade.aragog.Aragog.RemoveUser:output_type -> github.com.scaletrade.aragog.RemoveResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aragog_aragog_proto_init() }
func file_aragog_aragog_proto_init() {
	if File_aragog_aragog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aragog_aragog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aragog_aragog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aragog_aragog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aragog_aragog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aragog_aragog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aragog_aragog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aragog_aragog_proto_goTypes,
		DependencyIndexes: file_aragog_aragog_proto_depIdxs,
		MessageInfos:      file_aragog_aragog_proto_msgTypes,
	}.Build()
	File_aragog_aragog_proto = out.File
	file_aragog_aragog_proto_rawDesc = nil
	file_aragog_aragog_proto_goTypes = nil
	file_aragog_aragog_proto_depIdxs = nil
}
